// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: rms-library.proto

package rms_library

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// тип медиа - фильм или сериал
type MovieType int32

const (
	MovieType_TvSeries MovieType = 0
	MovieType_Film     MovieType = 1
)

// Enum value maps for MovieType.
var (
	MovieType_name = map[int32]string{
		0: "TvSeries",
		1: "Film",
	}
	MovieType_value = map[string]int32{
		"TvSeries": 0,
		"Film":     1,
	}
)

func (x MovieType) Enum() *MovieType {
	p := new(MovieType)
	*p = x
	return p
}

func (x MovieType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovieType) Descriptor() protoreflect.EnumDescriptor {
	return file_rms_library_proto_enumTypes[0].Descriptor()
}

func (MovieType) Type() protoreflect.EnumType {
	return &file_rms_library_proto_enumTypes[0]
}

func (x MovieType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovieType.Descriptor instead.
func (MovieType) EnumDescriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{0}
}

type GetMoviesRequest_AllowedTypes int32

const (
	GetMoviesRequest_Films    GetMoviesRequest_AllowedTypes = 0
	GetMoviesRequest_TvSeries GetMoviesRequest_AllowedTypes = 1
	GetMoviesRequest_Both     GetMoviesRequest_AllowedTypes = 2
)

// Enum value maps for GetMoviesRequest_AllowedTypes.
var (
	GetMoviesRequest_AllowedTypes_name = map[int32]string{
		0: "Films",
		1: "TvSeries",
		2: "Both",
	}
	GetMoviesRequest_AllowedTypes_value = map[string]int32{
		"Films":    0,
		"TvSeries": 1,
		"Both":     2,
	}
)

func (x GetMoviesRequest_AllowedTypes) Enum() *GetMoviesRequest_AllowedTypes {
	p := new(GetMoviesRequest_AllowedTypes)
	*p = x
	return p
}

func (x GetMoviesRequest_AllowedTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetMoviesRequest_AllowedTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_rms_library_proto_enumTypes[1].Descriptor()
}

func (GetMoviesRequest_AllowedTypes) Type() protoreflect.EnumType {
	return &file_rms_library_proto_enumTypes[1]
}

func (x GetMoviesRequest_AllowedTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetMoviesRequest_AllowedTypes.Descriptor instead.
func (GetMoviesRequest_AllowedTypes) EnumDescriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{13, 0}
}

// запрос на поиск во внешних источниках
type SearchMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text  string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *SearchMovieRequest) Reset() {
	*x = SearchMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMovieRequest) ProtoMessage() {}

func (x *SearchMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMovieRequest.ProtoReflect.Descriptor instead.
func (*SearchMovieRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{0}
}

func (x *SearchMovieRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchMovieRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// структура описывает общую информацию о фильме/сериале
type MovieInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Year        uint32    `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Poster      string    `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"`
	Genres      []string  `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	Rating      float32   `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Type        MovieType `protobuf:"varint,7,opt,name=type,proto3,enum=MovieType" json:"type,omitempty"`
	Seasons     *uint32   `protobuf:"varint,8,opt,name=seasons,proto3,oneof" json:"seasons,omitempty"`
}

func (x *MovieInfo) Reset() {
	*x = MovieInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieInfo) ProtoMessage() {}

func (x *MovieInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieInfo.ProtoReflect.Descriptor instead.
func (*MovieInfo) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{1}
}

func (x *MovieInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MovieInfo) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MovieInfo) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *MovieInfo) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MovieInfo) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MovieInfo) GetType() MovieType {
	if x != nil {
		return x.Type
	}
	return MovieType_TvSeries
}

func (x *MovieInfo) GetSeasons() uint32 {
	if x != nil && x.Seasons != nil {
		return *x.Seasons
	}
	return 0
}

// результат поиска по внешних источниках
type FoundMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сквозной ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// общая информация о Movie
	Info *MovieInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// информация о скачанных сезонах
	SeasonsDownloaded []uint32 `protobuf:"varint,3,rep,packed,name=seasonsDownloaded,proto3" json:"seasonsDownloaded,omitempty"`
}

func (x *FoundMovie) Reset() {
	*x = FoundMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoundMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundMovie) ProtoMessage() {}

func (x *FoundMovie) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundMovie.ProtoReflect.Descriptor instead.
func (*FoundMovie) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{2}
}

func (x *FoundMovie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FoundMovie) GetInfo() *MovieInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *FoundMovie) GetSeasonsDownloaded() []uint32 {
	if x != nil {
		return x.SeasonsDownloaded
	}
	return nil
}

// результат поиска - несколько вариантов фильма/сериала
type SearchMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movies []*FoundMovie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
}

func (x *SearchMovieResponse) Reset() {
	*x = SearchMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMovieResponse) ProtoMessage() {}

func (x *SearchMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMovieResponse.ProtoReflect.Descriptor instead.
func (*SearchMovieResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{3}
}

func (x *SearchMovieResponse) GetMovies() []*FoundMovie {
	if x != nil {
		return x.Movies
	}
	return nil
}

// раздача на торренте
type Torrent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID для идентификации данной раздачи
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// заголовок раздачи
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// размер раздачи в мегабайтах
	Size uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// кол-во раздающих
	Seeders uint32 `protobuf:"varint,4,opt,name=seeders,proto3" json:"seeders,omitempty"`
}

func (x *Torrent) Reset() {
	*x = Torrent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Torrent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torrent) ProtoMessage() {}

func (x *Torrent) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torrent.ProtoReflect.Descriptor instead.
func (*Torrent) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{4}
}

func (x *Torrent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Torrent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Torrent) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Torrent) GetSeeders() uint32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

// скачать указанный фильм, или сезон сериала
type DownloadMovieAutoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сквозной ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// какой сезон скачать, если не указан - скачать отсутствующие в библиотеке сезоны
	Season *uint32 `protobuf:"varint,2,opt,name=season,proto3,oneof" json:"season,omitempty"`
}

func (x *DownloadMovieAutoRequest) Reset() {
	*x = DownloadMovieAutoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadMovieAutoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMovieAutoRequest) ProtoMessage() {}

func (x *DownloadMovieAutoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMovieAutoRequest.ProtoReflect.Descriptor instead.
func (*DownloadMovieAutoRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadMovieAutoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadMovieAutoRequest) GetSeason() uint32 {
	if x != nil && x.Season != nil {
		return *x.Season
	}
	return 0
}

type DownloadMovieAutoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// удалось ли найти раздачи
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// какие сезоны были поставлены на закачку
	Seasons []uint32 `protobuf:"varint,2,rep,packed,name=seasons,proto3" json:"seasons,omitempty"`
}

func (x *DownloadMovieAutoResponse) Reset() {
	*x = DownloadMovieAutoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadMovieAutoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMovieAutoResponse) ProtoMessage() {}

func (x *DownloadMovieAutoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMovieAutoResponse.ProtoReflect.Descriptor instead.
func (*DownloadMovieAutoResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadMovieAutoResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DownloadMovieAutoResponse) GetSeasons() []uint32 {
	if x != nil {
		return x.Seasons
	}
	return nil
}

type FindMovieTorrentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сквозной ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// максимальное кол-во раздач в ответе
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// возможность указать конкретный сезон
	Season *uint32 `protobuf:"varint,3,opt,name=season,proto3,oneof" json:"season,omitempty"`
}

func (x *FindMovieTorrentsRequest) Reset() {
	*x = FindMovieTorrentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindMovieTorrentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMovieTorrentsRequest) ProtoMessage() {}

func (x *FindMovieTorrentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMovieTorrentsRequest.ProtoReflect.Descriptor instead.
func (*FindMovieTorrentsRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{7}
}

func (x *FindMovieTorrentsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FindMovieTorrentsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindMovieTorrentsRequest) GetSeason() uint32 {
	if x != nil && x.Season != nil {
		return *x.Season
	}
	return 0
}

type FindTorrentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// что ищем
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// сколько максимум раздач
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// строгое соответствие поисковому запросу
	Strong bool `protobuf:"varint,3,opt,name=strong,proto3" json:"strong,omitempty"`
}

func (x *FindTorrentsRequest) Reset() {
	*x = FindTorrentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindTorrentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTorrentsRequest) ProtoMessage() {}

func (x *FindTorrentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTorrentsRequest.ProtoReflect.Descriptor instead.
func (*FindTorrentsRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{8}
}

func (x *FindTorrentsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *FindTorrentsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindTorrentsRequest) GetStrong() bool {
	if x != nil {
		return x.Strong
	}
	return false
}

type FindTorrentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// найденные раздачи
	Results []*Torrent `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *FindTorrentsResponse) Reset() {
	*x = FindTorrentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindTorrentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTorrentsResponse) ProtoMessage() {}

func (x *FindTorrentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTorrentsResponse.ProtoReflect.Descriptor instead.
func (*FindTorrentsResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{9}
}

func (x *FindTorrentsResponse) GetResults() []*Torrent {
	if x != nil {
		return x.Results
	}
	return nil
}

type DownloadTorrentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID раздачи
	TorrentId string `protobuf:"bytes,1,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
}

func (x *DownloadTorrentRequest) Reset() {
	*x = DownloadTorrentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTorrentRequest) ProtoMessage() {}

func (x *DownloadTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTorrentRequest.ProtoReflect.Descriptor instead.
func (*DownloadTorrentRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadTorrentRequest) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

// инфа о новых сезонах одного сериала
type TvSeriesUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сквозной ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// общая информация о Movie
	Info *MovieInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// перечисление новых доступных сезонов
	SeasonsAvailable []uint32 `protobuf:"varint,3,rep,packed,name=seasonsAvailable,proto3" json:"seasonsAvailable,omitempty"`
}

func (x *TvSeriesUpdate) Reset() {
	*x = TvSeriesUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TvSeriesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TvSeriesUpdate) ProtoMessage() {}

func (x *TvSeriesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TvSeriesUpdate.ProtoReflect.Descriptor instead.
func (*TvSeriesUpdate) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{11}
}

func (x *TvSeriesUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TvSeriesUpdate) GetInfo() *MovieInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *TvSeriesUpdate) GetSeasonsAvailable() []uint32 {
	if x != nil {
		return x.SeasonsAvailable
	}
	return nil
}

// результат запроса обновления сериалов
type GetTvSeriesUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*TvSeriesUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *GetTvSeriesUpdatesResponse) Reset() {
	*x = GetTvSeriesUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTvSeriesUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTvSeriesUpdatesResponse) ProtoMessage() {}

func (x *GetTvSeriesUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTvSeriesUpdatesResponse.ProtoReflect.Descriptor instead.
func (*GetTvSeriesUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{12}
}

func (x *GetTvSeriesUpdatesResponse) GetUpdates() []*TvSeriesUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

// запрос доступных киношек в библиотеке
type GetMoviesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// какого типа элементы отображать
	Types GetMoviesRequest_AllowedTypes `protobuf:"varint,1,opt,name=types,proto3,enum=GetMoviesRequest_AllowedTypes" json:"types,omitempty"`
	// поиск по жанрам
	Genre *string `protobuf:"bytes,2,opt,name=genre,proto3,oneof" json:"genre,omitempty"`
}

func (x *GetMoviesRequest) Reset() {
	*x = GetMoviesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesRequest) ProtoMessage() {}

func (x *GetMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{13}
}

func (x *GetMoviesRequest) GetTypes() GetMoviesRequest_AllowedTypes {
	if x != nil {
		return x.Types
	}
	return GetMoviesRequest_Films
}

func (x *GetMoviesRequest) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

type FilmLayout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TorrentID string   `protobuf:"bytes,1,opt,name=torrentID,proto3" json:"torrentID,omitempty"`
	Files     []string `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *FilmLayout) Reset() {
	*x = FilmLayout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilmLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilmLayout) ProtoMessage() {}

func (x *FilmLayout) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilmLayout.ProtoReflect.Descriptor instead.
func (*FilmLayout) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{14}
}

func (x *FilmLayout) GetTorrentID() string {
	if x != nil {
		return x.TorrentID
	}
	return ""
}

func (x *FilmLayout) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type TvSeriesLayout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seasons map[uint32]*TvSeriesLayout_Season `protobuf:"bytes,1,rep,name=seasons,proto3" json:"seasons,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TvSeriesLayout) Reset() {
	*x = TvSeriesLayout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TvSeriesLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TvSeriesLayout) ProtoMessage() {}

func (x *TvSeriesLayout) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TvSeriesLayout.ProtoReflect.Descriptor instead.
func (*TvSeriesLayout) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{15}
}

func (x *TvSeriesLayout) GetSeasons() map[uint32]*TvSeriesLayout_Season {
	if x != nil {
		return x.Seasons
	}
	return nil
}

type Movie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID фильма или сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// общая информация о Movie
	Info *MovieInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// набор файлов фильма
	Film *FilmLayout `protobuf:"bytes,3,opt,name=film,proto3,oneof" json:"film,omitempty"`
	// набор файлов сериала
	TvSeries *TvSeriesLayout `protobuf:"bytes,4,opt,name=tvSeries,proto3,oneof" json:"tvSeries,omitempty"`
}

func (x *Movie) Reset() {
	*x = Movie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{16}
}

func (x *Movie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movie) GetInfo() *MovieInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Movie) GetFilm() *FilmLayout {
	if x != nil {
		return x.Film
	}
	return nil
}

func (x *Movie) GetTvSeries() *TvSeriesLayout {
	if x != nil {
		return x.TvSeries
	}
	return nil
}

type GetMoviesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*Movie `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *GetMoviesResponse) Reset() {
	*x = GetMoviesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesResponse) ProtoMessage() {}

func (x *GetMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetMoviesResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{17}
}

func (x *GetMoviesResponse) GetResult() []*Movie {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{18}
}

func (x *GetMovieRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Movie `protobuf:"bytes,1,opt,name=result,proto3,oneof" json:"result,omitempty"`
}

func (x *GetMovieResponse) Reset() {
	*x = GetMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResponse) ProtoMessage() {}

func (x *GetMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResponse.ProtoReflect.Descriptor instead.
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{19}
}

func (x *GetMovieResponse) GetResult() *Movie {
	if x != nil {
		return x.Result
	}
	return nil
}

type TvSeriesLayout_Season struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []string `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *TvSeriesLayout_Season) Reset() {
	*x = TvSeriesLayout_Season{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TvSeriesLayout_Season) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TvSeriesLayout_Season) ProtoMessage() {}

func (x *TvSeriesLayout_Season) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TvSeriesLayout_Season.ProtoReflect.Descriptor instead.
func (*TvSeriesLayout_Season) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{15, 0}
}

func (x *TvSeriesLayout_Season) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_rms_library_proto protoreflect.FileDescriptor

var file_rms_library_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x6d, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3e, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0xea, 0x01, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x6a, 0x0a,
	0x0a, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x73,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x11, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x22, 0x3a, 0x0a, 0x13, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x06, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x73, 0x22, 0x5d, 0x0a, 0x07, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x65, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x65,
	0x64, 0x65, 0x72, 0x73, 0x22, 0x52, 0x0a, 0x18, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1b, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x4b, 0x0a, 0x19, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x68, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x59, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x22, 0x3a, 0x0a, 0x14, 0x46, 0x69,
	0x6e, 0x64, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x36, 0x0a, 0x16, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x6c,
	0x0a, 0x0e, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x10, 0x73, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x47, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x76,
	0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x12, 0x19, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x88, 0x01, 0x01, 0x22, 0x31, 0x0a, 0x0c, 0x41,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x46,
	0x69, 0x6c, 0x6d, 0x73, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x6f, 0x74, 0x68, 0x10, 0x02, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x22, 0x40, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x6d,
	0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x0e, 0x54,
	0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x36, 0x0a,
	0x07, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e,
	0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x73, 0x1a, 0x1e, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x52, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa5, 0x01, 0x0a, 0x05, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x46, 0x69, 0x6c, 0x6d, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x48, 0x00,
	0x52, 0x04, 0x66, 0x69, 0x6c, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x08, 0x74, 0x76, 0x53,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x76,
	0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x48, 0x01, 0x52, 0x08,
	0x74, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x66, 0x69, 0x6c, 0x6d, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x74, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x22, 0x33, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x42, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x88,
	0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x23, 0x0a,
	0x09, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x76,
	0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x6d,
	0x10, 0x01, 0x32, 0x8a, 0x04, 0x0a, 0x0a, 0x52, 0x6d, 0x73, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x12, 0x38, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x12, 0x13, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x41, 0x75, 0x74, 0x6f,
	0x12, 0x19, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x41, 0x75, 0x74, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x6f,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x17,
	0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x49, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x10, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x72, 0x6d, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rms_library_proto_rawDescOnce sync.Once
	file_rms_library_proto_rawDescData = file_rms_library_proto_rawDesc
)

func file_rms_library_proto_rawDescGZIP() []byte {
	file_rms_library_proto_rawDescOnce.Do(func() {
		file_rms_library_proto_rawDescData = protoimpl.X.CompressGZIP(file_rms_library_proto_rawDescData)
	})
	return file_rms_library_proto_rawDescData
}

var file_rms_library_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rms_library_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_rms_library_proto_goTypes = []interface{}{
	(MovieType)(0),                     // 0: MovieType
	(GetMoviesRequest_AllowedTypes)(0), // 1: GetMoviesRequest.AllowedTypes
	(*SearchMovieRequest)(nil),         // 2: SearchMovieRequest
	(*MovieInfo)(nil),                  // 3: MovieInfo
	(*FoundMovie)(nil),                 // 4: FoundMovie
	(*SearchMovieResponse)(nil),        // 5: SearchMovieResponse
	(*Torrent)(nil),                    // 6: Torrent
	(*DownloadMovieAutoRequest)(nil),   // 7: DownloadMovieAutoRequest
	(*DownloadMovieAutoResponse)(nil),  // 8: DownloadMovieAutoResponse
	(*FindMovieTorrentsRequest)(nil),   // 9: FindMovieTorrentsRequest
	(*FindTorrentsRequest)(nil),        // 10: FindTorrentsRequest
	(*FindTorrentsResponse)(nil),       // 11: FindTorrentsResponse
	(*DownloadTorrentRequest)(nil),     // 12: DownloadTorrentRequest
	(*TvSeriesUpdate)(nil),             // 13: TvSeriesUpdate
	(*GetTvSeriesUpdatesResponse)(nil), // 14: GetTvSeriesUpdatesResponse
	(*GetMoviesRequest)(nil),           // 15: GetMoviesRequest
	(*FilmLayout)(nil),                 // 16: FilmLayout
	(*TvSeriesLayout)(nil),             // 17: TvSeriesLayout
	(*Movie)(nil),                      // 18: Movie
	(*GetMoviesResponse)(nil),          // 19: GetMoviesResponse
	(*GetMovieRequest)(nil),            // 20: GetMovieRequest
	(*GetMovieResponse)(nil),           // 21: GetMovieResponse
	(*TvSeriesLayout_Season)(nil),      // 22: TvSeriesLayout.Season
	nil,                                // 23: TvSeriesLayout.SeasonsEntry
	(*emptypb.Empty)(nil),              // 24: google.protobuf.Empty
}
var file_rms_library_proto_depIdxs = []int32{
	0,  // 0: MovieInfo.type:type_name -> MovieType
	3,  // 1: FoundMovie.info:type_name -> MovieInfo
	4,  // 2: SearchMovieResponse.movies:type_name -> FoundMovie
	6,  // 3: FindTorrentsResponse.results:type_name -> Torrent
	3,  // 4: TvSeriesUpdate.info:type_name -> MovieInfo
	13, // 5: GetTvSeriesUpdatesResponse.updates:type_name -> TvSeriesUpdate
	1,  // 6: GetMoviesRequest.types:type_name -> GetMoviesRequest.AllowedTypes
	23, // 7: TvSeriesLayout.seasons:type_name -> TvSeriesLayout.SeasonsEntry
	3,  // 8: Movie.info:type_name -> MovieInfo
	16, // 9: Movie.film:type_name -> FilmLayout
	17, // 10: Movie.tvSeries:type_name -> TvSeriesLayout
	18, // 11: GetMoviesResponse.result:type_name -> Movie
	18, // 12: GetMovieResponse.result:type_name -> Movie
	22, // 13: TvSeriesLayout.SeasonsEntry.value:type_name -> TvSeriesLayout.Season
	2,  // 14: RmsLibrary.SearchMovie:input_type -> SearchMovieRequest
	7,  // 15: RmsLibrary.DownloadMovieAuto:input_type -> DownloadMovieAutoRequest
	9,  // 16: RmsLibrary.FindMovieTorrents:input_type -> FindMovieTorrentsRequest
	10, // 17: RmsLibrary.FindTorrents:input_type -> FindTorrentsRequest
	12, // 18: RmsLibrary.DownloadTorrent:input_type -> DownloadTorrentRequest
	24, // 19: RmsLibrary.GetTvSeriesUpdates:input_type -> google.protobuf.Empty
	15, // 20: RmsLibrary.GetMovies:input_type -> GetMoviesRequest
	20, // 21: RmsLibrary.GetMovie:input_type -> GetMovieRequest
	5,  // 22: RmsLibrary.SearchMovie:output_type -> SearchMovieResponse
	8,  // 23: RmsLibrary.DownloadMovieAuto:output_type -> DownloadMovieAutoResponse
	11, // 24: RmsLibrary.FindMovieTorrents:output_type -> FindTorrentsResponse
	11, // 25: RmsLibrary.FindTorrents:output_type -> FindTorrentsResponse
	24, // 26: RmsLibrary.DownloadTorrent:output_type -> google.protobuf.Empty
	14, // 27: RmsLibrary.GetTvSeriesUpdates:output_type -> GetTvSeriesUpdatesResponse
	19, // 28: RmsLibrary.GetMovies:output_type -> GetMoviesResponse
	21, // 29: RmsLibrary.GetMovie:output_type -> GetMovieResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_rms_library_proto_init() }
func file_rms_library_proto_init() {
	if File_rms_library_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rms_library_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoundMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Torrent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadMovieAutoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadMovieAutoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindMovieTorrentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindTorrentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindTorrentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadTorrentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TvSeriesUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTvSeriesUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilmLayout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TvSeriesLayout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Movie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TvSeriesLayout_Season); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rms_library_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[13].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[16].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[19].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rms_library_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rms_library_proto_goTypes,
		DependencyIndexes: file_rms_library_proto_depIdxs,
		EnumInfos:         file_rms_library_proto_enumTypes,
		MessageInfos:      file_rms_library_proto_msgTypes,
	}.Build()
	File_rms_library_proto = out.File
	file_rms_library_proto_rawDesc = nil
	file_rms_library_proto_goTypes = nil
	file_rms_library_proto_depIdxs = nil
}
