// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.1
// source: rms-library.proto

package rms_library

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// список тайтлов
type List int32

const (
	// любимые тайтлы
	List_Favourites List = 0
	// список "к просмотру"
	List_WatchList List = 1
	// архив раздач
	List_Archive List = 2
)

// Enum value maps for List.
var (
	List_name = map[int32]string{
		0: "Favourites",
		1: "WatchList",
		2: "Archive",
	}
	List_value = map[string]int32{
		"Favourites": 0,
		"WatchList":  1,
		"Archive":    2,
	}
)

func (x List) Enum() *List {
	p := new(List)
	*p = x
	return p
}

func (x List) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (List) Descriptor() protoreflect.EnumDescriptor {
	return file_rms_library_proto_enumTypes[0].Descriptor()
}

func (List) Type() protoreflect.EnumType {
	return &file_rms_library_proto_enumTypes[0]
}

func (x List) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use List.Descriptor instead.
func (List) EnumDescriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{0}
}

type ContentType int32

const (
	// видео - фильмы/сериалы/клипы
	ContentType_TypeMovies ContentType = 0
	// музыка
	ContentType_TypeMusic ContentType = 1
	// разное
	ContentType_TypeOther ContentType = 2
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "TypeMovies",
		1: "TypeMusic",
		2: "TypeOther",
	}
	ContentType_value = map[string]int32{
		"TypeMovies": 0,
		"TypeMusic":  1,
		"TypeOther":  2,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_rms_library_proto_enumTypes[1].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_rms_library_proto_enumTypes[1]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{1}
}

// тип медиа - фильм или сериал
type MovieType int32

const (
	MovieType_TvSeries MovieType = 0
	MovieType_Film     MovieType = 1
	MovieType_Clip     MovieType = 2
)

// Enum value maps for MovieType.
var (
	MovieType_name = map[int32]string{
		0: "TvSeries",
		1: "Film",
		2: "Clip",
	}
	MovieType_value = map[string]int32{
		"TvSeries": 0,
		"Film":     1,
		"Clip":     2,
	}
)

func (x MovieType) Enum() *MovieType {
	p := new(MovieType)
	*p = x
	return p
}

func (x MovieType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovieType) Descriptor() protoreflect.EnumDescriptor {
	return file_rms_library_proto_enumTypes[2].Descriptor()
}

func (MovieType) Type() protoreflect.EnumType {
	return &file_rms_library_proto_enumTypes[2]
}

func (x MovieType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovieType.Descriptor instead.
func (MovieType) EnumDescriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{2}
}

type Pagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// смещение относительно первого результата
	Offset uint32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// максимальное кол-во элементов
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListsAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// глобальный идентификатор тайтла
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// в какой список добавляем тайтл
	List List `protobuf:"varint,2,opt,name=list,proto3,enum=List" json:"list,omitempty"`
}

func (x *ListsAddRequest) Reset() {
	*x = ListsAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListsAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListsAddRequest) ProtoMessage() {}

func (x *ListsAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListsAddRequest.ProtoReflect.Descriptor instead.
func (*ListsAddRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{1}
}

func (x *ListsAddRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListsAddRequest) GetList() List {
	if x != nil {
		return x.List
	}
	return List_Favourites
}

type ListsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// элементы какого списка отобразить
	List List `protobuf:"varint,1,opt,name=list,proto3,enum=List" json:"list,omitempty"`
	// тип медиа
	ContentType *ContentType `protobuf:"varint,2,opt,name=contentType,proto3,enum=ContentType,oneof" json:"contentType,omitempty"`
	// разбиение на страницы
	Pagination *Pagination `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
}

func (x *ListsListRequest) Reset() {
	*x = ListsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListsListRequest) ProtoMessage() {}

func (x *ListsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListsListRequest.ProtoReflect.Descriptor instead.
func (*ListsListRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{2}
}

func (x *ListsListRequest) GetList() List {
	if x != nil {
		return x.List
	}
	return List_Favourites
}

func (x *ListsListRequest) GetContentType() ContentType {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ContentType_TypeMovies
}

func (x *ListsListRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// идентификатор
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// название
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// тип медиа
	ContentType ContentType `protobuf:"varint,3,opt,name=contentType,proto3,enum=ContentType" json:"contentType,omitempty"`
	// занимаемое на диске место (Мб)
	Size uint64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{3}
}

func (x *ListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListItem) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_TypeMovies
}

func (x *ListItem) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// тайтлы
	Items []*ListItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListsListResponse) Reset() {
	*x = ListsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListsListResponse) ProtoMessage() {}

func (x *ListsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListsListResponse.ProtoReflect.Descriptor instead.
func (*ListsListResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{4}
}

func (x *ListsListResponse) GetItems() []*ListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListsMoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// идентификатор
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// в какой список переместить
	List List `protobuf:"varint,2,opt,name=list,proto3,enum=List" json:"list,omitempty"`
}

func (x *ListsMoveRequest) Reset() {
	*x = ListsMoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListsMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListsMoveRequest) ProtoMessage() {}

func (x *ListsMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListsMoveRequest.ProtoReflect.Descriptor instead.
func (*ListsMoveRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{5}
}

func (x *ListsMoveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListsMoveRequest) GetList() List {
	if x != nil {
		return x.List
	}
	return List_Favourites
}

type ListsDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// идентификатор
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListsDeleteRequest) Reset() {
	*x = ListsDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListsDeleteRequest) ProtoMessage() {}

func (x *ListsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListsDeleteRequest.ProtoReflect.Descriptor instead.
func (*ListsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{6}
}

func (x *ListsDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TorrentsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// идентификатор тайтла
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TorrentsListRequest) Reset() {
	*x = TorrentsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentsListRequest) ProtoMessage() {}

func (x *TorrentsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentsListRequest.ProtoReflect.Descriptor instead.
func (*TorrentsListRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{7}
}

func (x *TorrentsListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// раздача на торренте
type Torrent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID для идентификации данной раздачи
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// заголовок раздачи
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// размер раздачи в мегабайтах
	Size uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// кол-во раздающих
	Seeders uint32 `protobuf:"varint,4,opt,name=seeders,proto3" json:"seeders,omitempty"`
}

func (x *Torrent) Reset() {
	*x = Torrent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Torrent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torrent) ProtoMessage() {}

func (x *Torrent) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torrent.ProtoReflect.Descriptor instead.
func (*Torrent) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{8}
}

func (x *Torrent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Torrent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Torrent) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Torrent) GetSeeders() uint32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

type TorrentsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Torrents []*Torrent `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
}

func (x *TorrentsListResponse) Reset() {
	*x = TorrentsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentsListResponse) ProtoMessage() {}

func (x *TorrentsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentsListResponse.ProtoReflect.Descriptor instead.
func (*TorrentsListResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{9}
}

func (x *TorrentsListResponse) GetTorrents() []*Torrent {
	if x != nil {
		return x.Torrents
	}
	return nil
}

type TorrentsReplaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// идентификатор тайтла
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// идентификатор раздачи
	TorrentId string `protobuf:"bytes,2,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
	// идентификатор новой раздачи
	NewTorrentId *string `protobuf:"bytes,3,opt,name=newTorrentId,proto3,oneof" json:"newTorrentId,omitempty"`
	// торрент-файл для замены
	TorrentFile []byte `protobuf:"bytes,4,opt,name=torrentFile,proto3,oneof" json:"torrentFile,omitempty"`
}

func (x *TorrentsReplaceRequest) Reset() {
	*x = TorrentsReplaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentsReplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentsReplaceRequest) ProtoMessage() {}

func (x *TorrentsReplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentsReplaceRequest.ProtoReflect.Descriptor instead.
func (*TorrentsReplaceRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{10}
}

func (x *TorrentsReplaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TorrentsReplaceRequest) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

func (x *TorrentsReplaceRequest) GetNewTorrentId() string {
	if x != nil && x.NewTorrentId != nil {
		return *x.NewTorrentId
	}
	return ""
}

func (x *TorrentsReplaceRequest) GetTorrentFile() []byte {
	if x != nil {
		return x.TorrentFile
	}
	return nil
}

type TorrentsFindAlternativesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// идентификатор тайтла
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// идентификатор раздачи
	TorrentId string `protobuf:"bytes,2,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
}

func (x *TorrentsFindAlternativesRequest) Reset() {
	*x = TorrentsFindAlternativesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentsFindAlternativesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentsFindAlternativesRequest) ProtoMessage() {}

func (x *TorrentsFindAlternativesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentsFindAlternativesRequest.ProtoReflect.Descriptor instead.
func (*TorrentsFindAlternativesRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{11}
}

func (x *TorrentsFindAlternativesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TorrentsFindAlternativesRequest) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

type TorrentsFindAlternativesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Torrents []*Torrent `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
}

func (x *TorrentsFindAlternativesResponse) Reset() {
	*x = TorrentsFindAlternativesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentsFindAlternativesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentsFindAlternativesResponse) ProtoMessage() {}

func (x *TorrentsFindAlternativesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentsFindAlternativesResponse.ProtoReflect.Descriptor instead.
func (*TorrentsFindAlternativesResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{12}
}

func (x *TorrentsFindAlternativesResponse) GetTorrents() []*Torrent {
	if x != nil {
		return x.Torrents
	}
	return nil
}

type TorrentsAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// идентификатор тайтла
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// идентификатор новой раздачи
	NewTorrentId string `protobuf:"bytes,2,opt,name=newTorrentId,proto3" json:"newTorrentId,omitempty"`
	// торрент-файл для замены
	TorrentFile []byte `protobuf:"bytes,3,opt,name=torrentFile,proto3,oneof" json:"torrentFile,omitempty"`
}

func (x *TorrentsAddRequest) Reset() {
	*x = TorrentsAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentsAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentsAddRequest) ProtoMessage() {}

func (x *TorrentsAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentsAddRequest.ProtoReflect.Descriptor instead.
func (*TorrentsAddRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{13}
}

func (x *TorrentsAddRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TorrentsAddRequest) GetNewTorrentId() string {
	if x != nil {
		return x.NewTorrentId
	}
	return ""
}

func (x *TorrentsAddRequest) GetTorrentFile() []byte {
	if x != nil {
		return x.TorrentFile
	}
	return nil
}

type TorrentsDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// идентификатор тайтла
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// идентификатор раздачи
	TorrentId string `protobuf:"bytes,2,opt,name=torrentId,proto3" json:"torrentId,omitempty"`
}

func (x *TorrentsDeleteRequest) Reset() {
	*x = TorrentsDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TorrentsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentsDeleteRequest) ProtoMessage() {}

func (x *TorrentsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentsDeleteRequest.ProtoReflect.Descriptor instead.
func (*TorrentsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{14}
}

func (x *TorrentsDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TorrentsDeleteRequest) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

// запрос на поиск во внешних источниках
type MoviesSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text  string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *MoviesSearchRequest) Reset() {
	*x = MoviesSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoviesSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoviesSearchRequest) ProtoMessage() {}

func (x *MoviesSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoviesSearchRequest.ProtoReflect.Descriptor instead.
func (*MoviesSearchRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{15}
}

func (x *MoviesSearchRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MoviesSearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// структура описывает общую информацию о фильме/сериале
type MovieInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title         string    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Year          uint32    `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Poster        string    `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"`
	Genres        []string  `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	Rating        float32   `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Type          MovieType `protobuf:"varint,7,opt,name=type,proto3,enum=MovieType" json:"type,omitempty"`
	Seasons       *uint32   `protobuf:"varint,8,opt,name=seasons,proto3,oneof" json:"seasons,omitempty"`
	OriginalTitle string    `protobuf:"bytes,9,opt,name=originalTitle,proto3" json:"originalTitle,omitempty"`
}

func (x *MovieInfo) Reset() {
	*x = MovieInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieInfo) ProtoMessage() {}

func (x *MovieInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieInfo.ProtoReflect.Descriptor instead.
func (*MovieInfo) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{16}
}

func (x *MovieInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MovieInfo) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MovieInfo) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *MovieInfo) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MovieInfo) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MovieInfo) GetType() MovieType {
	if x != nil {
		return x.Type
	}
	return MovieType_TvSeries
}

func (x *MovieInfo) GetSeasons() uint32 {
	if x != nil && x.Seasons != nil {
		return *x.Seasons
	}
	return 0
}

func (x *MovieInfo) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

// результат поиска по внешних источниках
type FoundMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сквозной ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// общая информация о Movie
	Info *MovieInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// информация о скачанных сезонах
	SeasonsDownloaded []uint32 `protobuf:"varint,3,rep,packed,name=seasonsDownloaded,proto3" json:"seasonsDownloaded,omitempty"`
}

func (x *FoundMovie) Reset() {
	*x = FoundMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoundMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundMovie) ProtoMessage() {}

func (x *FoundMovie) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundMovie.ProtoReflect.Descriptor instead.
func (*FoundMovie) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{17}
}

func (x *FoundMovie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FoundMovie) GetInfo() *MovieInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *FoundMovie) GetSeasonsDownloaded() []uint32 {
	if x != nil {
		return x.SeasonsDownloaded
	}
	return nil
}

// результат поиска - несколько вариантов фильма/сериала
type MoviesSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movies []*FoundMovie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
}

func (x *MoviesSearchResponse) Reset() {
	*x = MoviesSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoviesSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoviesSearchResponse) ProtoMessage() {}

func (x *MoviesSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoviesSearchResponse.ProtoReflect.Descriptor instead.
func (*MoviesSearchResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{18}
}

func (x *MoviesSearchResponse) GetMovies() []*FoundMovie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type MoviesGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// идентификатор тайтла
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MoviesGetRequest) Reset() {
	*x = MoviesGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoviesGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoviesGetRequest) ProtoMessage() {}

func (x *MoviesGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoviesGetRequest.ProtoReflect.Descriptor instead.
func (*MoviesGetRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{19}
}

func (x *MoviesGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MoviesGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// информация о тайтле
	Info *MovieInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *MoviesGetResponse) Reset() {
	*x = MoviesGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoviesGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoviesGetResponse) ProtoMessage() {}

func (x *MoviesGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoviesGetResponse.ProtoReflect.Descriptor instead.
func (*MoviesGetResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{20}
}

func (x *MoviesGetResponse) GetInfo() *MovieInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// инфа о новых сезонах одного сериала
type TvSeriesUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сквозной ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// общая информация о Movie
	Info *MovieInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// перечисление новых доступных сезонов
	SeasonsAvailable []uint32 `protobuf:"varint,3,rep,packed,name=seasonsAvailable,proto3" json:"seasonsAvailable,omitempty"`
}

func (x *TvSeriesUpdate) Reset() {
	*x = TvSeriesUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TvSeriesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TvSeriesUpdate) ProtoMessage() {}

func (x *TvSeriesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TvSeriesUpdate.ProtoReflect.Descriptor instead.
func (*TvSeriesUpdate) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{21}
}

func (x *TvSeriesUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TvSeriesUpdate) GetInfo() *MovieInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *TvSeriesUpdate) GetSeasonsAvailable() []uint32 {
	if x != nil {
		return x.SeasonsAvailable
	}
	return nil
}

// результат запроса обновления сериалов
type MoviesGetUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*TvSeriesUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *MoviesGetUpdatesResponse) Reset() {
	*x = MoviesGetUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoviesGetUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoviesGetUpdatesResponse) ProtoMessage() {}

func (x *MoviesGetUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoviesGetUpdatesResponse.ProtoReflect.Descriptor instead.
func (*MoviesGetUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{22}
}

func (x *MoviesGetUpdatesResponse) GetUpdates() []*TvSeriesUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type Artist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Poster string `protobuf:"bytes,3,opt,name=poster,proto3" json:"poster,omitempty"`
	Albums uint32 `protobuf:"varint,4,opt,name=albums,proto3" json:"albums,omitempty"`
}

func (x *Artist) Reset() {
	*x = Artist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{23}
}

func (x *Artist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *Artist) GetAlbums() uint32 {
	if x != nil {
		return x.Albums
	}
	return 0
}

type Album struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Artist      string   `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Title       string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Poster      string   `protobuf:"bytes,5,opt,name=poster,proto3" json:"poster,omitempty"`
	ReleaseDate string   `protobuf:"bytes,6,opt,name=releaseDate,proto3" json:"releaseDate,omitempty"`
	Genres      []string `protobuf:"bytes,7,rep,name=genres,proto3" json:"genres,omitempty"`
	Tracks      uint32   `protobuf:"varint,8,opt,name=tracks,proto3" json:"tracks,omitempty"`
}

func (x *Album) Reset() {
	*x = Album{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{24}
}

func (x *Album) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Album) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Album) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Album) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Album) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *Album) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Album) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Album) GetTracks() uint32 {
	if x != nil {
		return x.Tracks
	}
	return 0
}

type MusicSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// текстовая строка поиска
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// ограничение на кол-во результатов
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *MusicSearchRequest) Reset() {
	*x = MusicSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusicSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicSearchRequest) ProtoMessage() {}

func (x *MusicSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicSearchRequest.ProtoReflect.Descriptor instead.
func (*MusicSearchRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{25}
}

func (x *MusicSearchRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MusicSearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MusicSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artists []*Artist `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	Albums  []*Album  `protobuf:"bytes,2,rep,name=albums,proto3" json:"albums,omitempty"`
}

func (x *MusicSearchResponse) Reset() {
	*x = MusicSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusicSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicSearchResponse) ProtoMessage() {}

func (x *MusicSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicSearchResponse.ProtoReflect.Descriptor instead.
func (*MusicSearchResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{26}
}

func (x *MusicSearchResponse) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *MusicSearchResponse) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

type MusicUpdates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// описание артиста
	Artist *Artist `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	// новые найденные альбомы
	Albums []*Album `protobuf:"bytes,2,rep,name=albums,proto3" json:"albums,omitempty"`
}

func (x *MusicUpdates) Reset() {
	*x = MusicUpdates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusicUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicUpdates) ProtoMessage() {}

func (x *MusicUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicUpdates.ProtoReflect.Descriptor instead.
func (*MusicUpdates) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{27}
}

func (x *MusicUpdates) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *MusicUpdates) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

type MusicGetUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*MusicUpdates `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *MusicGetUpdatesResponse) Reset() {
	*x = MusicGetUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MusicGetUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicGetUpdatesResponse) ProtoMessage() {}

func (x *MusicGetUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicGetUpdatesResponse.ProtoReflect.Descriptor instead.
func (*MusicGetUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{28}
}

func (x *MusicGetUpdatesResponse) GetUpdates() []*MusicUpdates {
	if x != nil {
		return x.Updates
	}
	return nil
}

type OtherSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// текст для поиска
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// ограничение кол-ва результатов
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *OtherSearchRequest) Reset() {
	*x = OtherSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtherSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherSearchRequest) ProtoMessage() {}

func (x *OtherSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherSearchRequest.ProtoReflect.Descriptor instead.
func (*OtherSearchRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{29}
}

func (x *OtherSearchRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OtherSearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type OtherSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Torrents []*Torrent `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
}

func (x *OtherSearchResponse) Reset() {
	*x = OtherSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtherSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherSearchResponse) ProtoMessage() {}

func (x *OtherSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherSearchResponse.ProtoReflect.Descriptor instead.
func (*OtherSearchResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{30}
}

func (x *OtherSearchResponse) GetTorrents() []*Torrent {
	if x != nil {
		return x.Torrents
	}
	return nil
}

var File_rms_library_proto protoreflect.FileDescriptor

var file_rms_library_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x6d, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3a, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xb3, 0x01, 0x0a, 0x10, 0x4c,
	0x69, 0x73, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x30, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x01, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x74, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x34, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x3d, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x73, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x25, 0x0a, 0x13, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5d, 0x0a, 0x07, 0x54, 0x6f, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x73, 0x65, 0x65, 0x64, 0x65, 0x72, 0x73, 0x22, 0x3c, 0x0a, 0x14, 0x54, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x24, 0x0a, 0x08, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x74, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x16, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27,
	0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x54, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01, 0x52, 0x0b,
	0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0f,
	0x0a, 0x0d, 0x5f, 0x6e, 0x65, 0x77, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x22,
	0x4f, 0x0a, 0x1f, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x48, 0x0a, 0x20, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x08, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x52, 0x08, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x7f, 0x0a, 0x12, 0x54, 0x6f,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x54, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0b, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x45, 0x0a, 0x15, 0x54,
	0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x22, 0x3f, 0x0a, 0x13, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x90, 0x02, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x73, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x6a, 0x0a, 0x0a, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x11, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x64, 0x22, 0x3b, 0x0a, 0x14, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x46, 0x6f, 0x75,
	0x6e, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x22,
	0x22, 0x0a, 0x10, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x11, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x6c, 0x0a, 0x0e, 0x54, 0x76, 0x53, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x10, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x45, 0x0a, 0x18, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73,
	0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x22, 0x5c, 0x0a,
	0x06, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0xc3, 0x01, 0x0a, 0x05,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x73, 0x22, 0x3e, 0x0a, 0x12, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x58, 0x0a, 0x13, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x06, 0x61,
	0x6c, 0x62, 0x75, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x41, 0x6c,
	0x62, 0x75, 0x6d, 0x52, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0x4f, 0x0a, 0x0c, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x06, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x06,
	0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x52, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0x42, 0x0a, 0x17,
	0x4d, 0x75, 0x73, 0x69, 0x63, 0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x22, 0x3e, 0x0a, 0x12, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x3b, 0x0a, 0x13, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x08, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x6f, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x52, 0x08, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x2a, 0x32, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69,
	0x74, 0x65, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x10,
	0x02, 0x2a, 0x3b, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x02, 0x2a, 0x2d,
	0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x54,
	0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x69, 0x6c,
	0x6d, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x6c, 0x69, 0x70, 0x10, 0x02, 0x32, 0xd1, 0x01,
	0x0a, 0x05, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x10,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x11, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12,
	0x11, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x35, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x32, 0xc2, 0x02, 0x0a, 0x08, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x33,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x54,
	0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x17,
	0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x57, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69,
	0x76, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12,
	0x13, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x54, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xae, 0x01, 0x0a, 0x06, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x12, 0x35, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x11, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x73, 0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x7c, 0x0a, 0x05, 0x4d, 0x75, 0x73, 0x69, 0x63,
	0x12, 0x33, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x13, 0x2e, 0x4d, 0x75, 0x73,
	0x69, 0x63, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x4d, 0x75,
	0x73, 0x69, 0x63, 0x47, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x3c, 0x0a, 0x05, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x33,
	0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x13, 0x2e, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x4f, 0x74, 0x68, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x72, 0x6d, 0x73, 0x2d, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rms_library_proto_rawDescOnce sync.Once
	file_rms_library_proto_rawDescData = file_rms_library_proto_rawDesc
)

func file_rms_library_proto_rawDescGZIP() []byte {
	file_rms_library_proto_rawDescOnce.Do(func() {
		file_rms_library_proto_rawDescData = protoimpl.X.CompressGZIP(file_rms_library_proto_rawDescData)
	})
	return file_rms_library_proto_rawDescData
}

var file_rms_library_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rms_library_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_rms_library_proto_goTypes = []interface{}{
	(List)(0),                                // 0: List
	(ContentType)(0),                         // 1: ContentType
	(MovieType)(0),                           // 2: MovieType
	(*Pagination)(nil),                       // 3: Pagination
	(*ListsAddRequest)(nil),                  // 4: ListsAddRequest
	(*ListsListRequest)(nil),                 // 5: ListsListRequest
	(*ListItem)(nil),                         // 6: ListItem
	(*ListsListResponse)(nil),                // 7: ListsListResponse
	(*ListsMoveRequest)(nil),                 // 8: ListsMoveRequest
	(*ListsDeleteRequest)(nil),               // 9: ListsDeleteRequest
	(*TorrentsListRequest)(nil),              // 10: TorrentsListRequest
	(*Torrent)(nil),                          // 11: Torrent
	(*TorrentsListResponse)(nil),             // 12: TorrentsListResponse
	(*TorrentsReplaceRequest)(nil),           // 13: TorrentsReplaceRequest
	(*TorrentsFindAlternativesRequest)(nil),  // 14: TorrentsFindAlternativesRequest
	(*TorrentsFindAlternativesResponse)(nil), // 15: TorrentsFindAlternativesResponse
	(*TorrentsAddRequest)(nil),               // 16: TorrentsAddRequest
	(*TorrentsDeleteRequest)(nil),            // 17: TorrentsDeleteRequest
	(*MoviesSearchRequest)(nil),              // 18: MoviesSearchRequest
	(*MovieInfo)(nil),                        // 19: MovieInfo
	(*FoundMovie)(nil),                       // 20: FoundMovie
	(*MoviesSearchResponse)(nil),             // 21: MoviesSearchResponse
	(*MoviesGetRequest)(nil),                 // 22: MoviesGetRequest
	(*MoviesGetResponse)(nil),                // 23: MoviesGetResponse
	(*TvSeriesUpdate)(nil),                   // 24: TvSeriesUpdate
	(*MoviesGetUpdatesResponse)(nil),         // 25: MoviesGetUpdatesResponse
	(*Artist)(nil),                           // 26: Artist
	(*Album)(nil),                            // 27: Album
	(*MusicSearchRequest)(nil),               // 28: MusicSearchRequest
	(*MusicSearchResponse)(nil),              // 29: MusicSearchResponse
	(*MusicUpdates)(nil),                     // 30: MusicUpdates
	(*MusicGetUpdatesResponse)(nil),          // 31: MusicGetUpdatesResponse
	(*OtherSearchRequest)(nil),               // 32: OtherSearchRequest
	(*OtherSearchResponse)(nil),              // 33: OtherSearchResponse
	(*emptypb.Empty)(nil),                    // 34: google.protobuf.Empty
}
var file_rms_library_proto_depIdxs = []int32{
	0,  // 0: ListsAddRequest.list:type_name -> List
	0,  // 1: ListsListRequest.list:type_name -> List
	1,  // 2: ListsListRequest.contentType:type_name -> ContentType
	3,  // 3: ListsListRequest.pagination:type_name -> Pagination
	1,  // 4: ListItem.contentType:type_name -> ContentType
	6,  // 5: ListsListResponse.items:type_name -> ListItem
	0,  // 6: ListsMoveRequest.list:type_name -> List
	11, // 7: TorrentsListResponse.torrents:type_name -> Torrent
	11, // 8: TorrentsFindAlternativesResponse.torrents:type_name -> Torrent
	2,  // 9: MovieInfo.type:type_name -> MovieType
	19, // 10: FoundMovie.info:type_name -> MovieInfo
	20, // 11: MoviesSearchResponse.movies:type_name -> FoundMovie
	19, // 12: MoviesGetResponse.info:type_name -> MovieInfo
	19, // 13: TvSeriesUpdate.info:type_name -> MovieInfo
	24, // 14: MoviesGetUpdatesResponse.updates:type_name -> TvSeriesUpdate
	26, // 15: MusicSearchResponse.artists:type_name -> Artist
	27, // 16: MusicSearchResponse.albums:type_name -> Album
	26, // 17: MusicUpdates.artist:type_name -> Artist
	27, // 18: MusicUpdates.albums:type_name -> Album
	30, // 19: MusicGetUpdatesResponse.updates:type_name -> MusicUpdates
	11, // 20: OtherSearchResponse.torrents:type_name -> Torrent
	4,  // 21: Lists.Add:input_type -> ListsAddRequest
	5,  // 22: Lists.List:input_type -> ListsListRequest
	8,  // 23: Lists.Move:input_type -> ListsMoveRequest
	9,  // 24: Lists.Delete:input_type -> ListsDeleteRequest
	10, // 25: Torrents.List:input_type -> TorrentsListRequest
	13, // 26: Torrents.Replace:input_type -> TorrentsReplaceRequest
	14, // 27: Torrents.FindAlternatives:input_type -> TorrentsFindAlternativesRequest
	16, // 28: Torrents.Add:input_type -> TorrentsAddRequest
	17, // 29: Torrents.Delete:input_type -> TorrentsDeleteRequest
	18, // 30: Movies.Search:input_type -> MoviesSearchRequest
	22, // 31: Movies.Get:input_type -> MoviesGetRequest
	34, // 32: Movies.GetUpdates:input_type -> google.protobuf.Empty
	28, // 33: Music.Search:input_type -> MusicSearchRequest
	34, // 34: Music.GetUpdates:input_type -> google.protobuf.Empty
	32, // 35: Other.Search:input_type -> OtherSearchRequest
	34, // 36: Lists.Add:output_type -> google.protobuf.Empty
	7,  // 37: Lists.List:output_type -> ListsListResponse
	34, // 38: Lists.Move:output_type -> google.protobuf.Empty
	34, // 39: Lists.Delete:output_type -> google.protobuf.Empty
	12, // 40: Torrents.List:output_type -> TorrentsListResponse
	34, // 41: Torrents.Replace:output_type -> google.protobuf.Empty
	15, // 42: Torrents.FindAlternatives:output_type -> TorrentsFindAlternativesResponse
	34, // 43: Torrents.Add:output_type -> google.protobuf.Empty
	34, // 44: Torrents.Delete:output_type -> google.protobuf.Empty
	21, // 45: Movies.Search:output_type -> MoviesSearchResponse
	23, // 46: Movies.Get:output_type -> MoviesGetResponse
	25, // 47: Movies.GetUpdates:output_type -> MoviesGetUpdatesResponse
	29, // 48: Music.Search:output_type -> MusicSearchResponse
	31, // 49: Music.GetUpdates:output_type -> MusicGetUpdatesResponse
	33, // 50: Other.Search:output_type -> OtherSearchResponse
	36, // [36:51] is the sub-list for method output_type
	21, // [21:36] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_rms_library_proto_init() }
func file_rms_library_proto_init() {
	if File_rms_library_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rms_library_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListsAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListsMoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListsDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Torrent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentsReplaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentsFindAlternativesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentsFindAlternativesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentsAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TorrentsDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoviesSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoundMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoviesSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoviesGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoviesGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TvSeriesUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoviesGetUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Album); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusicSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusicSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusicUpdates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MusicGetUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtherSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtherSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rms_library_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[13].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rms_library_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_rms_library_proto_goTypes,
		DependencyIndexes: file_rms_library_proto_depIdxs,
		EnumInfos:         file_rms_library_proto_enumTypes,
		MessageInfos:      file_rms_library_proto_msgTypes,
	}.Build()
	File_rms_library_proto = out.File
	file_rms_library_proto_rawDesc = nil
	file_rms_library_proto_goTypes = nil
	file_rms_library_proto_depIdxs = nil
}
