// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: rms-library.proto

package rms_library

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for RmsLibrary service

func NewRmsLibraryEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for RmsLibrary service

type RmsLibraryService interface {
	// поиск информации о фильмах и сериалах во внешних источниках
	SearchMovie(ctx context.Context, in *SearchMovieRequest, opts ...client.CallOption) (*SearchMovieResponse, error)
	// скачать указанный фильм или сериал
	DownloadMovie(ctx context.Context, in *DownloadMovieRequest, opts ...client.CallOption) (*DownloadMovieResponse, error)
	// получить список доступных новых сезонов для скачивания
	GetTvSeriesUpdates(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*GetTvSeriesUpdatesResponse, error)
	// получить информацию о фильме/сериале по его ID
	GetMovieInfo(ctx context.Context, in *GetMovieInfoRequest, opts ...client.CallOption) (*MovieInfo, error)
	// получить список всех фильмов/сериалов
	GetMovies(ctx context.Context, in *GetMoviesRequest, opts ...client.CallOption) (*GetMoviesResponse, error)
	// получить раскладку директорий, связанную с тем как хранится контент
	GetMovieLayout(ctx context.Context, in *GetMovieLayoutRequest, opts ...client.CallOption) (*GetMovieLayoutResponse, error)
}

type rmsLibraryService struct {
	c    client.Client
	name string
}

func NewRmsLibraryService(name string, c client.Client) RmsLibraryService {
	return &rmsLibraryService{
		c:    c,
		name: name,
	}
}

func (c *rmsLibraryService) SearchMovie(ctx context.Context, in *SearchMovieRequest, opts ...client.CallOption) (*SearchMovieResponse, error) {
	req := c.c.NewRequest(c.name, "RmsLibrary.SearchMovie", in)
	out := new(SearchMovieResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rmsLibraryService) DownloadMovie(ctx context.Context, in *DownloadMovieRequest, opts ...client.CallOption) (*DownloadMovieResponse, error) {
	req := c.c.NewRequest(c.name, "RmsLibrary.DownloadMovie", in)
	out := new(DownloadMovieResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rmsLibraryService) GetTvSeriesUpdates(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*GetTvSeriesUpdatesResponse, error) {
	req := c.c.NewRequest(c.name, "RmsLibrary.GetTvSeriesUpdates", in)
	out := new(GetTvSeriesUpdatesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rmsLibraryService) GetMovieInfo(ctx context.Context, in *GetMovieInfoRequest, opts ...client.CallOption) (*MovieInfo, error) {
	req := c.c.NewRequest(c.name, "RmsLibrary.GetMovieInfo", in)
	out := new(MovieInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rmsLibraryService) GetMovies(ctx context.Context, in *GetMoviesRequest, opts ...client.CallOption) (*GetMoviesResponse, error) {
	req := c.c.NewRequest(c.name, "RmsLibrary.GetMovies", in)
	out := new(GetMoviesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rmsLibraryService) GetMovieLayout(ctx context.Context, in *GetMovieLayoutRequest, opts ...client.CallOption) (*GetMovieLayoutResponse, error) {
	req := c.c.NewRequest(c.name, "RmsLibrary.GetMovieLayout", in)
	out := new(GetMovieLayoutResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RmsLibrary service

type RmsLibraryHandler interface {
	// поиск информации о фильмах и сериалах во внешних источниках
	SearchMovie(context.Context, *SearchMovieRequest, *SearchMovieResponse) error
	// скачать указанный фильм или сериал
	DownloadMovie(context.Context, *DownloadMovieRequest, *DownloadMovieResponse) error
	// получить список доступных новых сезонов для скачивания
	GetTvSeriesUpdates(context.Context, *emptypb.Empty, *GetTvSeriesUpdatesResponse) error
	// получить информацию о фильме/сериале по его ID
	GetMovieInfo(context.Context, *GetMovieInfoRequest, *MovieInfo) error
	// получить список всех фильмов/сериалов
	GetMovies(context.Context, *GetMoviesRequest, *GetMoviesResponse) error
	// получить раскладку директорий, связанную с тем как хранится контент
	GetMovieLayout(context.Context, *GetMovieLayoutRequest, *GetMovieLayoutResponse) error
}

func RegisterRmsLibraryHandler(s server.Server, hdlr RmsLibraryHandler, opts ...server.HandlerOption) error {
	type rmsLibrary interface {
		SearchMovie(ctx context.Context, in *SearchMovieRequest, out *SearchMovieResponse) error
		DownloadMovie(ctx context.Context, in *DownloadMovieRequest, out *DownloadMovieResponse) error
		GetTvSeriesUpdates(ctx context.Context, in *emptypb.Empty, out *GetTvSeriesUpdatesResponse) error
		GetMovieInfo(ctx context.Context, in *GetMovieInfoRequest, out *MovieInfo) error
		GetMovies(ctx context.Context, in *GetMoviesRequest, out *GetMoviesResponse) error
		GetMovieLayout(ctx context.Context, in *GetMovieLayoutRequest, out *GetMovieLayoutResponse) error
	}
	type RmsLibrary struct {
		rmsLibrary
	}
	h := &rmsLibraryHandler{hdlr}
	return s.Handle(s.NewHandler(&RmsLibrary{h}, opts...))
}

type rmsLibraryHandler struct {
	RmsLibraryHandler
}

func (h *rmsLibraryHandler) SearchMovie(ctx context.Context, in *SearchMovieRequest, out *SearchMovieResponse) error {
	return h.RmsLibraryHandler.SearchMovie(ctx, in, out)
}

func (h *rmsLibraryHandler) DownloadMovie(ctx context.Context, in *DownloadMovieRequest, out *DownloadMovieResponse) error {
	return h.RmsLibraryHandler.DownloadMovie(ctx, in, out)
}

func (h *rmsLibraryHandler) GetTvSeriesUpdates(ctx context.Context, in *emptypb.Empty, out *GetTvSeriesUpdatesResponse) error {
	return h.RmsLibraryHandler.GetTvSeriesUpdates(ctx, in, out)
}

func (h *rmsLibraryHandler) GetMovieInfo(ctx context.Context, in *GetMovieInfoRequest, out *MovieInfo) error {
	return h.RmsLibraryHandler.GetMovieInfo(ctx, in, out)
}

func (h *rmsLibraryHandler) GetMovies(ctx context.Context, in *GetMoviesRequest, out *GetMoviesResponse) error {
	return h.RmsLibraryHandler.GetMovies(ctx, in, out)
}

func (h *rmsLibraryHandler) GetMovieLayout(ctx context.Context, in *GetMovieLayoutRequest, out *GetMovieLayoutResponse) error {
	return h.RmsLibraryHandler.GetMovieLayout(ctx, in, out)
}
