// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: rms-library.proto

package rms_library

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// тип медиа - фильм или сериал
type MovieType int32

const (
	MovieType_TvSeries MovieType = 0
	MovieType_Film     MovieType = 1
)

// Enum value maps for MovieType.
var (
	MovieType_name = map[int32]string{
		0: "TvSeries",
		1: "Film",
	}
	MovieType_value = map[string]int32{
		"TvSeries": 0,
		"Film":     1,
	}
)

func (x MovieType) Enum() *MovieType {
	p := new(MovieType)
	*p = x
	return p
}

func (x MovieType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovieType) Descriptor() protoreflect.EnumDescriptor {
	return file_rms_library_proto_enumTypes[0].Descriptor()
}

func (MovieType) Type() protoreflect.EnumType {
	return &file_rms_library_proto_enumTypes[0]
}

func (x MovieType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovieType.Descriptor instead.
func (MovieType) EnumDescriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{0}
}

type GetMoviesRequest_AllowedTypes int32

const (
	GetMoviesRequest_Films    GetMoviesRequest_AllowedTypes = 0
	GetMoviesRequest_TvSeries GetMoviesRequest_AllowedTypes = 1
	GetMoviesRequest_Both     GetMoviesRequest_AllowedTypes = 2
)

// Enum value maps for GetMoviesRequest_AllowedTypes.
var (
	GetMoviesRequest_AllowedTypes_name = map[int32]string{
		0: "Films",
		1: "TvSeries",
		2: "Both",
	}
	GetMoviesRequest_AllowedTypes_value = map[string]int32{
		"Films":    0,
		"TvSeries": 1,
		"Both":     2,
	}
)

func (x GetMoviesRequest_AllowedTypes) Enum() *GetMoviesRequest_AllowedTypes {
	p := new(GetMoviesRequest_AllowedTypes)
	*p = x
	return p
}

func (x GetMoviesRequest_AllowedTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetMoviesRequest_AllowedTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_rms_library_proto_enumTypes[1].Descriptor()
}

func (GetMoviesRequest_AllowedTypes) Type() protoreflect.EnumType {
	return &file_rms_library_proto_enumTypes[1]
}

func (x GetMoviesRequest_AllowedTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetMoviesRequest_AllowedTypes.Descriptor instead.
func (GetMoviesRequest_AllowedTypes) EnumDescriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{9, 0}
}

// запрос на поиск во внешних источниках
type SearchMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text  string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *SearchMovieRequest) Reset() {
	*x = SearchMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMovieRequest) ProtoMessage() {}

func (x *SearchMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMovieRequest.ProtoReflect.Descriptor instead.
func (*SearchMovieRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{0}
}

func (x *SearchMovieRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchMovieRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// структура описывает общую информацию о фильме/сериале
type MovieInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Year        uint32    `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Poster      string    `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"`
	Genres      []string  `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	Rating      float32   `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Type        MovieType `protobuf:"varint,7,opt,name=type,proto3,enum=MovieType" json:"type,omitempty"`
	Seasons     *uint32   `protobuf:"varint,8,opt,name=seasons,proto3,oneof" json:"seasons,omitempty"`
}

func (x *MovieInfo) Reset() {
	*x = MovieInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieInfo) ProtoMessage() {}

func (x *MovieInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieInfo.ProtoReflect.Descriptor instead.
func (*MovieInfo) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{1}
}

func (x *MovieInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MovieInfo) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MovieInfo) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *MovieInfo) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MovieInfo) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MovieInfo) GetType() MovieType {
	if x != nil {
		return x.Type
	}
	return MovieType_TvSeries
}

func (x *MovieInfo) GetSeasons() uint32 {
	if x != nil && x.Seasons != nil {
		return *x.Seasons
	}
	return 0
}

// запрос получения инфы о фильме/сериале по его ID
type GetMovieInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMovieInfoRequest) Reset() {
	*x = GetMovieInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieInfoRequest) ProtoMessage() {}

func (x *GetMovieInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMovieInfoRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{2}
}

func (x *GetMovieInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// результат поиска по внешних источниках
type FoundMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сквозной ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// общая информация о Movie
	Info *MovieInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// информация о скачанных сезонах
	SeasonsDownloaded []uint32 `protobuf:"varint,3,rep,packed,name=seasonsDownloaded,proto3" json:"seasonsDownloaded,omitempty"`
}

func (x *FoundMovie) Reset() {
	*x = FoundMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoundMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundMovie) ProtoMessage() {}

func (x *FoundMovie) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundMovie.ProtoReflect.Descriptor instead.
func (*FoundMovie) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{3}
}

func (x *FoundMovie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FoundMovie) GetInfo() *MovieInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *FoundMovie) GetSeasonsDownloaded() []uint32 {
	if x != nil {
		return x.SeasonsDownloaded
	}
	return nil
}

// результат поиска - несколько вариантов фильма/сериала
type SearchMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movies []*FoundMovie `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
}

func (x *SearchMovieResponse) Reset() {
	*x = SearchMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMovieResponse) ProtoMessage() {}

func (x *SearchMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMovieResponse.ProtoReflect.Descriptor instead.
func (*SearchMovieResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{4}
}

func (x *SearchMovieResponse) GetMovies() []*FoundMovie {
	if x != nil {
		return x.Movies
	}
	return nil
}

// скачать указанный фильм, или сезон сериала
type DownloadMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сквозной ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// скачать другую версию
	OtherVersion bool `protobuf:"varint,2,opt,name=otherVersion,proto3" json:"otherVersion,omitempty"`
	// какой сезон скачать, если не указан - скачать отсутствующие в библиотеке сезоны
	Season *uint32 `protobuf:"varint,3,opt,name=season,proto3,oneof" json:"season,omitempty"`
}

func (x *DownloadMovieRequest) Reset() {
	*x = DownloadMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMovieRequest) ProtoMessage() {}

func (x *DownloadMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMovieRequest.ProtoReflect.Descriptor instead.
func (*DownloadMovieRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadMovieRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadMovieRequest) GetOtherVersion() bool {
	if x != nil {
		return x.OtherVersion
	}
	return false
}

func (x *DownloadMovieRequest) GetSeason() uint32 {
	if x != nil && x.Season != nil {
		return *x.Season
	}
	return 0
}

type DownloadMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// удалось ли найти раздачи
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// какие сезоны были поставлены на закачку
	Seasons []uint32 `protobuf:"varint,2,rep,packed,name=seasons,proto3" json:"seasons,omitempty"`
}

func (x *DownloadMovieResponse) Reset() {
	*x = DownloadMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMovieResponse) ProtoMessage() {}

func (x *DownloadMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMovieResponse.ProtoReflect.Descriptor instead.
func (*DownloadMovieResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadMovieResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DownloadMovieResponse) GetSeasons() []uint32 {
	if x != nil {
		return x.Seasons
	}
	return nil
}

// инфа о новых сезонах одного сериала
type TvSeriesUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сквозной ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// общая информация о Movie
	Info *MovieInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// перечисление новых доступных сезонов
	SeasonsAvailable []uint32 `protobuf:"varint,3,rep,packed,name=seasonsAvailable,proto3" json:"seasonsAvailable,omitempty"`
}

func (x *TvSeriesUpdate) Reset() {
	*x = TvSeriesUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TvSeriesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TvSeriesUpdate) ProtoMessage() {}

func (x *TvSeriesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TvSeriesUpdate.ProtoReflect.Descriptor instead.
func (*TvSeriesUpdate) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{7}
}

func (x *TvSeriesUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TvSeriesUpdate) GetInfo() *MovieInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *TvSeriesUpdate) GetSeasonsAvailable() []uint32 {
	if x != nil {
		return x.SeasonsAvailable
	}
	return nil
}

// результат запроса обновления сериалов
type GetTvSeriesUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*TvSeriesUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *GetTvSeriesUpdatesResponse) Reset() {
	*x = GetTvSeriesUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTvSeriesUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTvSeriesUpdatesResponse) ProtoMessage() {}

func (x *GetTvSeriesUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTvSeriesUpdatesResponse.ProtoReflect.Descriptor instead.
func (*GetTvSeriesUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{8}
}

func (x *GetTvSeriesUpdatesResponse) GetUpdates() []*TvSeriesUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

// запрос доступных киношек в библиотеке
type GetMoviesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// какого типа элементы отображать
	Types GetMoviesRequest_AllowedTypes `protobuf:"varint,1,opt,name=types,proto3,enum=GetMoviesRequest_AllowedTypes" json:"types,omitempty"`
	// поиск по жанрам
	Genre *string `protobuf:"bytes,2,opt,name=genre,proto3,oneof" json:"genre,omitempty"`
}

func (x *GetMoviesRequest) Reset() {
	*x = GetMoviesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesRequest) ProtoMessage() {}

func (x *GetMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{9}
}

func (x *GetMoviesRequest) GetTypes() GetMoviesRequest_AllowedTypes {
	if x != nil {
		return x.Types
	}
	return GetMoviesRequest_Films
}

func (x *GetMoviesRequest) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

type GetMoviesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*FoundMovie `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *GetMoviesResponse) Reset() {
	*x = GetMoviesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesResponse) ProtoMessage() {}

func (x *GetMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetMoviesResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{10}
}

func (x *GetMoviesResponse) GetResults() []*FoundMovie {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetMovieLayoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID фильма/сериала
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Для сериала должны указать сезон
	Season *uint32 `protobuf:"varint,2,opt,name=season,proto3,oneof" json:"season,omitempty"`
}

func (x *GetMovieLayoutRequest) Reset() {
	*x = GetMovieLayoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieLayoutRequest) ProtoMessage() {}

func (x *GetMovieLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieLayoutRequest.ProtoReflect.Descriptor instead.
func (*GetMovieLayoutRequest) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{11}
}

func (x *GetMovieLayoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMovieLayoutRequest) GetSeason() uint32 {
	if x != nil && x.Season != nil {
		return *x.Season
	}
	return 0
}

type GetMovieLayoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMovieLayoutResponse) Reset() {
	*x = GetMovieLayoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rms_library_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieLayoutResponse) ProtoMessage() {}

func (x *GetMovieLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rms_library_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieLayoutResponse.ProtoReflect.Descriptor instead.
func (*GetMovieLayoutResponse) Descriptor() ([]byte, []int) {
	return file_rms_library_proto_rawDescGZIP(), []int{12}
}

var File_rms_library_proto protoreflect.FileDescriptor

var file_rms_library_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x6d, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3e, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0xea, 0x01, 0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x25, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x6a, 0x0a, 0x0a, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x11, 0x73,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x22, 0x3a, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x14,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6f, 0x74, 0x68, 0x65,
	0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x47, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x07, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x6c, 0x0a, 0x0e, 0x54, 0x76, 0x53,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x73,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x10, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x47, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x54, 0x76,
	0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x22, 0xa0, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x67,
	0x65, 0x6e, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x88, 0x01, 0x01, 0x22, 0x31, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x6d, 0x73, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x42, 0x6f, 0x74, 0x68, 0x10, 0x02, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x22, 0x3a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x46, 0x6f, 0x75, 0x6e,
	0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22,
	0x4f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x23, 0x0a, 0x09, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x76, 0x53, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x6d, 0x10, 0x01, 0x32,
	0xfa, 0x02, 0x0a, 0x0a, 0x52, 0x6d, 0x73, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12, 0x38,
	0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x13, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x15, 0x2e, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54,
	0x76, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x76, 0x53, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x73, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e,
	0x2e, 0x2e, 0x2f, 0x72, 0x6d, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rms_library_proto_rawDescOnce sync.Once
	file_rms_library_proto_rawDescData = file_rms_library_proto_rawDesc
)

func file_rms_library_proto_rawDescGZIP() []byte {
	file_rms_library_proto_rawDescOnce.Do(func() {
		file_rms_library_proto_rawDescData = protoimpl.X.CompressGZIP(file_rms_library_proto_rawDescData)
	})
	return file_rms_library_proto_rawDescData
}

var file_rms_library_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rms_library_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rms_library_proto_goTypes = []interface{}{
	(MovieType)(0),                     // 0: MovieType
	(GetMoviesRequest_AllowedTypes)(0), // 1: GetMoviesRequest.AllowedTypes
	(*SearchMovieRequest)(nil),         // 2: SearchMovieRequest
	(*MovieInfo)(nil),                  // 3: MovieInfo
	(*GetMovieInfoRequest)(nil),        // 4: GetMovieInfoRequest
	(*FoundMovie)(nil),                 // 5: FoundMovie
	(*SearchMovieResponse)(nil),        // 6: SearchMovieResponse
	(*DownloadMovieRequest)(nil),       // 7: DownloadMovieRequest
	(*DownloadMovieResponse)(nil),      // 8: DownloadMovieResponse
	(*TvSeriesUpdate)(nil),             // 9: TvSeriesUpdate
	(*GetTvSeriesUpdatesResponse)(nil), // 10: GetTvSeriesUpdatesResponse
	(*GetMoviesRequest)(nil),           // 11: GetMoviesRequest
	(*GetMoviesResponse)(nil),          // 12: GetMoviesResponse
	(*GetMovieLayoutRequest)(nil),      // 13: GetMovieLayoutRequest
	(*GetMovieLayoutResponse)(nil),     // 14: GetMovieLayoutResponse
	(*emptypb.Empty)(nil),              // 15: google.protobuf.Empty
}
var file_rms_library_proto_depIdxs = []int32{
	0,  // 0: MovieInfo.type:type_name -> MovieType
	3,  // 1: FoundMovie.info:type_name -> MovieInfo
	5,  // 2: SearchMovieResponse.movies:type_name -> FoundMovie
	3,  // 3: TvSeriesUpdate.info:type_name -> MovieInfo
	9,  // 4: GetTvSeriesUpdatesResponse.updates:type_name -> TvSeriesUpdate
	1,  // 5: GetMoviesRequest.types:type_name -> GetMoviesRequest.AllowedTypes
	5,  // 6: GetMoviesResponse.results:type_name -> FoundMovie
	2,  // 7: RmsLibrary.SearchMovie:input_type -> SearchMovieRequest
	7,  // 8: RmsLibrary.DownloadMovie:input_type -> DownloadMovieRequest
	15, // 9: RmsLibrary.GetTvSeriesUpdates:input_type -> google.protobuf.Empty
	4,  // 10: RmsLibrary.GetMovieInfo:input_type -> GetMovieInfoRequest
	11, // 11: RmsLibrary.GetMovies:input_type -> GetMoviesRequest
	13, // 12: RmsLibrary.GetMovieLayout:input_type -> GetMovieLayoutRequest
	6,  // 13: RmsLibrary.SearchMovie:output_type -> SearchMovieResponse
	8,  // 14: RmsLibrary.DownloadMovie:output_type -> DownloadMovieResponse
	10, // 15: RmsLibrary.GetTvSeriesUpdates:output_type -> GetTvSeriesUpdatesResponse
	3,  // 16: RmsLibrary.GetMovieInfo:output_type -> MovieInfo
	12, // 17: RmsLibrary.GetMovies:output_type -> GetMoviesResponse
	14, // 18: RmsLibrary.GetMovieLayout:output_type -> GetMovieLayoutResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rms_library_proto_init() }
func file_rms_library_proto_init() {
	if File_rms_library_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rms_library_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoundMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TvSeriesUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTvSeriesUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieLayoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rms_library_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieLayoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rms_library_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_rms_library_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rms_library_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rms_library_proto_goTypes,
		DependencyIndexes: file_rms_library_proto_depIdxs,
		EnumInfos:         file_rms_library_proto_enumTypes,
		MessageInfos:      file_rms_library_proto_msgTypes,
	}.Build()
	File_rms_library_proto = out.File
	file_rms_library_proto_rawDesc = nil
	file_rms_library_proto_goTypes = nil
	file_rms_library_proto_depIdxs = nil
}
