// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: video.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transport int32

const (
	Transport_RTSP               Transport = 0
	Transport_HTTP_HLS_MPEGTS    Transport = 1
	Transport_HTTP_HLS_MP4       Transport = 2
	Transport_HTTP_HLS_ONE_CHUNK Transport = 3
	Transport_HTTP_MP4           Transport = 4
	Transport_HTTP_FLV           Transport = 5
	Transport_HTTP_MPEGTS        Transport = 6
	Transport_HTTP_DASH          Transport = 7
)

// Enum value maps for Transport.
var (
	Transport_name = map[int32]string{
		0: "RTSP",
		1: "HTTP_HLS_MPEGTS",
		2: "HTTP_HLS_MP4",
		3: "HTTP_HLS_ONE_CHUNK",
		4: "HTTP_MP4",
		5: "HTTP_FLV",
		6: "HTTP_MPEGTS",
		7: "HTTP_DASH",
	}
	Transport_value = map[string]int32{
		"RTSP":               0,
		"HTTP_HLS_MPEGTS":    1,
		"HTTP_HLS_MP4":       2,
		"HTTP_HLS_ONE_CHUNK": 3,
		"HTTP_MP4":           4,
		"HTTP_FLV":           5,
		"HTTP_MPEGTS":        6,
		"HTTP_DASH":          7,
	}
)

func (x Transport) Enum() *Transport {
	p := new(Transport)
	*p = x
	return p
}

func (x Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_video_proto_enumTypes[0].Descriptor()
}

func (Transport) Type() protoreflect.EnumType {
	return &file_video_proto_enumTypes[0]
}

func (x Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport.Descriptor instead.
func (Transport) EnumDescriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

var File_video_proto protoreflect.FileDescriptor

var file_video_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x2a, 0x90, 0x01, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x54, 0x53, 0x50, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x48, 0x54, 0x54, 0x50, 0x5f, 0x48, 0x4c, 0x53, 0x5f, 0x4d, 0x50, 0x45, 0x47, 0x54, 0x53, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x48, 0x4c, 0x53, 0x5f, 0x4d, 0x50,
	0x34, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x48, 0x4c, 0x53, 0x5f,
	0x4f, 0x4e, 0x45, 0x5f, 0x43, 0x48, 0x55, 0x4e, 0x4b, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x48,
	0x54, 0x54, 0x50, 0x5f, 0x4d, 0x50, 0x34, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x54, 0x54,
	0x50, 0x5f, 0x46, 0x4c, 0x56, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x54, 0x54, 0x50, 0x5f,
	0x4d, 0x50, 0x45, 0x47, 0x54, 0x53, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x54, 0x54, 0x50,
	0x5f, 0x44, 0x41, 0x53, 0x48, 0x10, 0x07, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x61, 0x63, 0x6f, 0x6f, 0x6e, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x6d, 0x73, 0x2d, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData = file_video_proto_rawDesc
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(file_video_proto_rawDescData)
	})
	return file_video_proto_rawDescData
}

var file_video_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_video_proto_goTypes = []interface{}{
	(Transport)(0), // 0: video.Transport
}
var file_video_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_video_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		EnumInfos:         file_video_proto_enumTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_rawDesc = nil
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
